INSERT OR IGNORE INTO words (id, word, definition, etymology, pronunciation, examples_json, created_at) VALUES
  (1, 'serendipity', 'The occurrence of events by chance in a happy or beneficial way.', 'Coined by Horace Walpole in 1754 after the Persian fairy tale "The Three Princes of Serendip".', 'ser-uhn-DIP-ih-tee', '["Finding that cafe was pure serendipity."]', '2024-01-01T00:00:00Z'),
  (2, 'luminous', 'Emitting or reflecting steady, clear light.', 'From Latin "lumen" meaning light.', 'LOO-muh-nus', '["The luminous dial glowed softly in the dark."]', '2024-01-01T00:00:00Z'),
  (3, 'resilience', 'The capacity to recover quickly from difficulties.', 'From Latin "resilire" meaning to rebound.', 'ri-ZIL-yuhns', '["Her resilience helped her adapt to change."]', '2024-01-01T00:00:00Z'),
  (4, 'ephemeral', 'Lasting for a very short time.', 'From Greek "ephemeros" meaning lasting a day.', 'ih-FEM-er-uhl', '["The beauty of the sunset was ephemeral."]', '2024-01-01T00:00:00Z'),
  (5, 'sonder', 'The realization that each passerby has a life as vivid as your own.', 'Coined in The Dictionary of Obscure Sorrows.', 'SON-der', '["She felt a wave of sonder on the busy street."]', '2024-01-01T00:00:00Z'),
  (6, 'candor', 'The quality of being open and honest.', 'From Latin "candor" meaning whiteness or purity.', 'KAN-der', '["He spoke with candor about the challenges."]', '2024-01-01T00:00:00Z'),
  (7, 'taciturn', 'Reserved or saying little.', 'From Latin "tacitus" meaning silent.', 'TAS-ih-turn', '["The taciturn guide nodded instead of speaking."]', '2024-01-01T00:00:00Z'),
  (8, 'verdant', 'Green with grass or vegetation.', 'From Old French "verdoyant" meaning green.', 'VER-dnt', '["A verdant valley stretched beyond the hills."]', '2024-01-01T00:00:00Z'),
  (9, 'mellifluous', 'Sweet or musical; pleasant to hear.', 'From Latin "mel" meaning honey and "fluere" meaning flow.', 'muh-LIF-loo-uhs', '["Her mellifluous voice filled the hall."]', '2024-01-01T00:00:00Z'),
  (10, 'quintessential', 'Representing the most perfect example.', 'From Latin "quinta essentia" meaning fifth essence.', 'kwin-tuh-SEN-shuhl', '["The cafe is the quintessential neighborhood spot."]', '2024-01-01T00:00:00Z'),
  (11, 'nostalgia', 'A sentimental longing for the past.', 'From Greek "nostos" (return) and "algos" (pain).', 'nos-TAL-juh', '["Old photos filled him with nostalgia."]', '2024-01-01T00:00:00Z'),
  (12, 'lucid', 'Expressed clearly; easy to understand.', 'From Latin "lucidus" meaning clear or light.', 'LOO-sid', '["She gave a lucid explanation of the plan."]', '2024-01-01T00:00:00Z'),
  (13, 'innate', 'Inborn; natural.', 'From Latin "innatus" meaning born in.', 'ih-NAYT', '["He had an innate curiosity."]', '2024-01-01T00:00:00Z'),
  (14, 'equanimity', 'Mental calmness and composure.', 'From Latin "aequanimitas" meaning evenness of mind.', 'ee-kwuh-NIM-uh-tee', '["She kept her equanimity during the crisis."]', '2024-01-01T00:00:00Z'),
  (15, 'eloquent', 'Fluent or persuasive in speaking or writing.', 'From Latin "eloquens" meaning speaking out.', 'EL-uh-kwent', '["His eloquent speech moved the audience."]', '2024-01-01T00:00:00Z'),
  (16, 'ambivalent', 'Having mixed feelings or contradictory ideas.', 'From Latin "ambi" (both) and "valere" (to be strong).', 'am-BIV-uh-lent', '["She felt ambivalent about the move."]', '2024-01-01T00:00:00Z'),
  (17, 'catharsis', 'The process of releasing strong emotions.', 'From Greek "katharsis" meaning purification.', 'kuh-THAR-sis', '["The story provided a catharsis for the audience."]', '2024-01-01T00:00:00Z'),
  (18, 'tenacious', 'Tending to keep a firm hold; persistent.', 'From Latin "tenax" meaning holding fast.', 'tuh-NAY-shus', '["Her tenacious effort paid off."]', '2024-01-01T00:00:00Z'),
  (19, 'solace', 'Comfort in a time of distress.', 'From Latin "solacium" meaning comfort.', 'SOL-iss', '["Music was a solace during the long night."]', '2024-01-01T00:00:00Z'),
  (20, 'ardent', 'Enthusiastic or passionate.', 'From Latin "ardere" meaning to burn.', 'AR-dent', '["He is an ardent supporter of the arts."]', '2024-01-01T00:00:00Z');
